/* MIDIRecUtils.h for Nightingale */

/* Structs used in the real-time MIDI and/or MIDI file functions */

typedef struct
{
	Byte 			noteNumber;
	Byte 			channel;
	Byte 			onVelocity;
	Byte 			offVelocity;
	long 			startTime;
	long 			duration;		/* in milliseconds	*/

} MNOTE, *MNOTEPTR;

typedef struct {
	Byte 			noteNumber;
	Byte 			onVelocity;
	Byte 			offVelocity;
	Boolean			first;			/* TRUE=this note starts a new chord */
	long 			duration;
} NOTEAUX;

typedef struct {
	LINK			link;			/* Sometimes used for an index into a NOTEAUX table */
	unsigned short	mult;			/* Duration as a multiple of some quantum */
	long			time;
	unsigned		added:1;		/* Note/chord segment generated by ClarAllToMeas? */
	unsigned		tupleNum:3;		/* If !0, this is first note of this kind of tuplet */
	unsigned		tupleDur:12;	/* Total duration of tuplet as multiple of quantum */
	unsigned short	tupleTime;		/* Time tuplet starts relative to start of this note */
} LINKTIMEINFO;


/* Prototypes */

INT16 FillMergeBuffer(LINK, LINKTIMEINFO [], INT16, Boolean);
Boolean MRMerge(Document *, INT16, LINKTIMEINFO *, INT16, LINKTIMEINFO *, INT16, LINK *);
